# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cd:
    runs-on: ubuntu-latest
    container:
      image: node

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t back .
      - name: Tags
        run: |
          docker tag back ${{ secrets.DOCKER_USER }}/somethingaboutmeweb:${{ github.sha }}
          docker tag back ${{ secrets.DOCKER_USER }}/somethingaboutmeweb:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/somethingaboutmeweb:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/somethingaboutmeweb:latest
