# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USER }} -p --password-stdin
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/somethingaboutmeweb:latest
      - name: Push the tagged Docker image
        run: docker push ${{ secrets.DOCKER_USER }}/somethingaboutmeweb:latest
